title: Ryujooh
description: Minimalist Digital Garden
baseurl: "" 
url: "https://ryujooh.github.io"

# GitHub Repository Info for management links
repository: ryujooh/ryujooh.github.io
branch: main

markdown: kramdown
permalink: /:title/

exclude:
  - README.md
  - .github
  - docs
