title: Ryujooh
description: Minimalist Digital Garden
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryujooh.github.io" # the base hostname & protocol for your site

markdown: kramdown
permalink: /:title/

# Jekyll build settings
exclude:
  - README.md
  - admin.html
  - .github
  - docs
